apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-cluster-gitops-application-set
  namespace: cluster-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - merge:
        generators:
          - list:
              elements:
                - name: "openshift-gitops-operator"
                  syncWave: "0"
                  folder: "cluster/openshift-gitops-operator"
                - name: "cluster-gitops"
                  syncWave: "10"
                  folder: "cluster/cluster-gitops"
                - name: "external-secrets-operator"
                  syncWave: "20"
                  folder: "cluster/external-secrets-operator"
                - name: "kube-descheduler"
                  syncWave: "20"
                  folder: "cluster/kube-descheduler"
                - name: "kubevirt-hyperconverged"
                  syncWave: "20"
                  folder: "cluster/kubevirt-hyperconverged"
                - name: "nmstate"
                  syncWave: "20"
                  folder: "cluster/nmstate"
                - name: "openshift-cert-manager-operator"
                  syncWave: "20"
                  folder: "cluster/openshift-cert-manager-operator"
                - name: "self-node-remediation"
                  syncWave: "20"
                  folder: "cluster/self-node-remediation"
          - list:
              elements:
                - repoURL: https://github.com/<org>/openshift-cluster-gitops.git
        mergeKeys:
          - ""
  template:
    metadata:
      name: '{{.name}}'
      namespace: cluster-gitops
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
    spec:
      project: cluster
      source:
        repoURL: '{{.repoURL}}'
        targetRevision: main
        path: '{{.folder}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: ''
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
